DEBUG 2016-03-16 17:36:32,595: 	 Executing command: 'submit'
DEBUG 2016-03-16 17:36:32,595: 	 Found CRAB cache file /afs/cern.ch/user/g/gkrintir/.crab3
DEBUG 2016-03-16 17:36:32,613: 	 Checking credentials
DEBUG 2016-03-16 17:36:32,613: 	 Found proxy file /tmp/x509up_u61469
DEBUG 2016-03-16 17:36:32,613: 	 Getting proxy life time left
DEBUG 2016-03-16 17:36:33,742: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u61469 -timeleft
 output : 43092

 error: 
 retcode : 0
DEBUG 2016-03-16 17:36:34,779: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u61469 -actimeleft
 output : 43090

 error: 
 retcode : 0
DEBUG 2016-03-16 17:36:34,779: 	 Proxy valid for 11:58:12 hours
INFO 2016-03-16 17:36:34,779: 	 Will use CRAB configuration file crabConfig_CMSSW_7_6_1_PCC_ZeroBias3.py
DEBUG 2016-03-16 17:36:34,779: 	 Loading CRAB configuration file.
DEBUG 2016-03-16 17:36:34,781: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-03-16 17:36:34,781: 	 Working area '/afs/cern.ch/user/g/gkrintir/github/PCCTools/CMSSW_7_6_1/src/RecoLuminosity/LumiProducer/test/analysis/test/Run2015E-PromptReco-v1/crab_CMSSW_7_6_1_PCC_ZeroBias3' already exists 
Please change the requestName in the config file
ERROR 2016-03-16 17:36:34,781: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1603.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1603.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1603.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 32, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1603.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 299, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1603.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/g/gkrintir/github/PCCTools/CMSSW_7_6_1/src/RecoLuminosity/LumiProducer/test/analysis/test/Run2015E-PromptReco-v1/crab_CMSSW_7_6_1_PCC_ZeroBias3' already exists 
Please change the requestName in the config file
